# Generated by Django 5.2.8 on 2026-01-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='travel_checklist_progress',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
