# Generated by Django 5.2.8 on 2026-01-27 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_pendingregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingregistration',
            name='otp_expires_at',
        ),
    ]
