# Generated by Django 5.2.8 on 2026-02-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_travel_checklist_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='expected_arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
