# Generated by Django 5.2.8 on 2026-02-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_pendingregistration_expected_arrival_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchecklist',
            name='progress',
        ),
        migrations.AddField(
            model_name='userchecklist',
            name='checked_items',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='userchecklist',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
