# Generated by Django 5.2.8 on 2026-03-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_rename_balance_wallet_foreign_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immutabletransaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('CONVERSION', 'Conversion'), ('TILL', 'M-Pesa Till'), ('PAYBILL', 'M-Pesa Paybill'), ('SEND_MONEY', 'M-Pesa Send Money')], max_length=20),
        ),
    ]
