# Generated by Django 5.2.8 on 2026-04-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_immutabletransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='immutabletransaction',
            name='withdrawal_method',
            field=models.CharField(blank=True, choices=[('CARD', 'Card'), ('APPLE_PAY', 'Apple Pay'), ('PAYPAL', 'PayPal')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='immutabletransaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('CONVERSION', 'Conversion'), ('TILL', 'M-Pesa Till'), ('PAYBILL', 'M-Pesa Paybill'), ('SEND_MONEY', 'M-Pesa Send Money'), ('WITHDRAWAL', 'Withdrawal')], max_length=20),
        ),
    ]
